apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: market-data
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - eu-central-1b
          - key: karpenter.sh/nodepool
            operator: In
            values:
            - generic
          - key: traderepublic.com/instancegroup
            operator: In
            values:
            - generic
  containers:
  - name: debug
    image: ubuntu:22.04
    command: ["/bin/bash"]
    args: ["-c", "apt-get update && apt-get install -y curl wget unzip vim net-tools iputils-ping dnsutils openjdk-11-jdk less && sleep infinity"]
    resources:
      requests:
        memory: "4Gi"
        cpu: "100m"
      limits:
        memory: "5Gi"
        cpu: "500m"
  restartPolicy: Never
